@api=http://localhost:3000/avance

GET {{api}}

POST {{api}}
Content-Type: application/json

{"idTrimestre": "28", 
"idUsuarioAplicativo": "3", 
"idSolicitud": "17",
"finalizado": "1"
}

DELETE  {{api}}
Content-Type: application/json

{"idSolicitud" : "1"}


PUT   {{api}}
Content-Type: application/json

{"idAvance": "7",
"idTrimestre": "28", 
"idUsuarioAplicativo": "3", 
"idSolicitud": "17",
"finalizado": "0",
"idUsuarioAplicativo_temp" :"1"
}

GET  {{api}}/4

