@api=http://localhost:3000/bitacoraAuditoria

GET {{api}}

POST {{api}}
Content-Type: application/json

{"idTransaccion": "", 
"descripcion": "", 
"idUsuarioAplicativo": "", 
"fechaHora": "", 
"idSolcitud": ""
}

DELETE  {{api}}
Content-Type: application/json

{"idSolicitud" : "1"}


PUT   {{api}}
Content-Type: application/json

{"idTransaccion": "", 
"descripcion": "", 
"idUsuarioAplicativo": "", 
"fechaHora": "", 
"idSolcitud": ""
}


GET  {{api}}/1

