@api=http://localhost:3000/departamento

GET {{api}}


POST {{api}}
Content-Type: application/json


{ "descripcion" : "prueba Valeria"

}

DELETE  {{api}}
Content-Type: application/json

{"idDepartamento" : "20"}


PUT   {{api}}
Content-Type: application/json

{"idDepartamento" : "20",
"descripcion" : "Otro"
}


GET  {{api}}/9