@api=http://localhost:3000/funcionario

GET {{api}}

POST {{api}}
Content-Type: application/json


{ "nombre": "Test", 
"apellidos": "Test", 
"fechaNacimiento": "", 
"idSexo": "", 
"loginName": "", 
"password": "",  
"foto": "", 
"idDepartamento": "", 
}

DELETE  {{api}}
Content-Type: application/json

{"idSexo" : "8"}


PUT   {{api}}
Content-Type: application/json

{"idFuncionario" : "9",
"nombre": "", 
"apellidos": "", 
"fechaNacimiento": "", 
"idSexo": "", 
"loginName": "", 
"password": "",  
"foto": "", 
"idDepartamento": "",
}


GET  {{api}}/1

