@api=http://localhost:3000/funcionario

GET {{api}}

POST {{api}}
Content-Type: application/json


{"nombre": "Test", 
"apellidos": "Test", 
"fechaNacimiento": "2019-05-30", 
"idSexo": "28", 
"loginName": "vale@gestion.org", 
"password": "123", 
"idDepartamento": "1"}

DELETE  {{api}}
Content-Type: application/json

{"idSexo" : "8"}


PUT   {{api}}
Content-Type: application/json

{"idFuncionario" : "1",
"nombre": "Test", 
"apellidos": "Test", 
"fechaNacimiento": "2019-05-30", 
"idSexo": "28", 
"loginName": "vale@gestion.org", 
"password": "124", 
"idDepartamento": "1"
}


GET  {{api}}/1

