@api=http://localhost:3000/sexo

GET {{api}}


POST {{api}}
Content-Type: application/json


{ "descripcion" : "prueba Valeria"

}

DELETE  {{api}}
Content-Type: application/json

{"idSexo" : "5"}


PUT   {{api}}
Content-Type: application/json

{"idSexo" : "5",
"descripcion" : "Otro"
}


GET  {{api}}/3