@api=http://localhost:3000/solicitud

GET {{api}}

POST {{api}}
Content-Type: application/json

{"idUsuarioAplicativo": "1", 
"idResponsableTI": "2", 
"fechaInicio": "2022-05-30", 
"fechaFin":  "2022-05-31",  
"idResponsableUsuarioFinal": "2"
}
    

PUT   {{api}}
Content-Type: application/json

{"idSolicitud" : "6",
"idUsuarioAplicativo": "1"
}


PUT   {{api}}
Content-Type: application/json

{"idSolicitud": "9",
"idUsuarioAplicativo": "1", 
"idResponsableTI": "2", 
"fechaInicio": "2022-05-31", 
"fechaFin":  "2022-05-31",  
"idResponsableUsuarioFinal": "7",
"idUsuarioAplicativo_temp" :"1"
}


GET  {{api}}/9

