@api=http://localhost:3000/transaccion

GET {{api}}


POST {{api}}
Content-Type: application/json


{ "descripcion" : "prueba Valeria"

}

DELETE  {{api}}
Content-Type: application/json

{"idTransaccion" : "26"}


PUT   {{api}}
Content-Type: application/json

{"idTransaccion" : "26",
"descripcion" : "Otro"
}


GET  {{api}}/26