@api=http://localhost:3000/trimestre

GET {{api}}


POST {{api}}
Content-Type: application/json


{ "descripcion" : "prueba Valeria 2"

}

DELETE  {{api}}
Content-Type: application/json

{"idTrimestre" : "6"}


PUT   {{api}}
Content-Type: application/json

{"idTrimestre" : "5",
"descripcion" : "Otro"
}


GET  {{api}}/5